### ISSUE TITLE
[BUG]run firefox in the github action

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1977]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Python version: [e.g. 3.7, 3.9]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```

**Describe the bug**

github action log
```
  File "/__t/Python/3.10.11/x64/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/__t/Python/3.10.11/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/__t/Python/3.10.11/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/__t/Python/3.10.11/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /ms-playwright/firefox-1403/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-wYr2u9 -juggler-pipe --no-sandbox -silent
<launched> pid=810
[pid=810][err] Error: no DISPLAY environment variable specified
[pid=810] <process did exit: exitCode=1, signal=null>
[pid=810] starting temporary directories cleanup
============================================================
Error: Process completed with exit code 1.
```

reproduce repo 
https://github.com/wanghaisheng/validate-your-proxy-against-ip-leak/blob/main/.github/workflows/test.yml

code snippets
![image](https://github.com/microsoft/playwright-python/assets/2363295/c55de193-dc2c-4f1a-9641-7bd333721134)

![image](https://github.com/microsoft/playwright-python/assets/2363295/e3c8ed70-76a9-42f3-ae91-b9d9591f8f2f)

try to fix following advice here

https://github.com/microsoft/playwright/issues/6500

**Comment by mxschmitt** [comment]
As the error shows, the browser is launched in headed mode, you need to either run it headless or with [xvfb-run](https://playwright.dev/python/docs/ci#running-headed).

**Comment by wanghaisheng** [comment]
@mxschmitt 

I have manually set headless  to be true
```


        self.driver = await async_playwright().start()
        print('self._headless:',self._headless)
        self.browser = await getattr(self.driver, self._driver_type).launch(
            headless=self._headless,
            args=["--no-sandbox"],
            proxy=proxy,
            executable_path=self._executable_path,
            downloads_path=self._download_path,
            firefox_user_prefs={
                "media.peerconnection.enabled": False,
                "media.navigator.enabled": False,
                "privacy.resistFingerprinting": False,
            } if self._driver_type=='firefox' 
            else None,
        )
```


log
Finished processing dependencies for tsup==0.1.16
sh: 1: start: not found
**self._headless: True**
Traceback (most recent call last):
  File "/__w/validate-your-proxy-against-ip-leak/validate-your-proxy-against-ip-leak/tiktoka-studio-uploader/examples/botcheck.py", line 574, in <module>
    asyncio.run(main())
  File "/__t/Python/3.10.12/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/__t/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/__w/validate-your-proxy-against-ip-leak/validate-your-proxy-against-ip-leak/tiktoka-studio-uploader/examples/botcheck.py", line 473, in main
    pl = await PlaywrightAsyncDriverStealth.create(
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/tsup-0.1.16-py3.10.egg/tsup/utils/webdriver/playwright_driver_async_stealth.py", line 218, in create
    await self._setup()
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/tsup-0.1.16-py3.10.egg/tsup/utils/webdriver/playwright_driver_async_stealth.py", line 115, in _setup
    self.browser = await getattr(self.driver, self._driver_type).launch(
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14476, in launch
    await self._impl_obj.launch(
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/__t/Python/3.10.12/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /ms-playwright/firefox-1403/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-5VV65x -juggler-pipe --no-sandbox -silent
<launched> pid=1082
[pid=1082][err] Error: no DISPLAY environment variable specified
[pid=1082] <process did exit: exitCode=1, signal=null>
[pid=1082] starting temporary directories cleanup
=========================================================

**Comment by wanghaisheng** [comment]
```
name: bot check screenshots
on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.35.0-jammy      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: 'wanghaisheng/tiktoka-studio-uploader'     
          path: tiktoka-studio-uploader 
          
#       - name: Run Playwright tests
#         uses: docker://mcr.microsoft.com/playwright:v1.35.0-jammy          
#https://github.com/juliangruber/browser-run/issues/147
      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: |
          apt-get update     
          apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          # start xvfb in the background
          /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
# https://stackoverflow.com/questions/63592708/error-no-display-environment-variable-specified
      #          apt-get install xvfb
 #         touch ~/.Xauthority
  #        xauth generate :0 . trusted
   #       xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)
    #      xauth list
     #     export DISPLAY=:0        
        run: |
          apt-get update     
          export DISPLAY=localhost:0.0
          export MOZ_HEADLESS=1    
          ls -al
          cd tiktoka-studio-uploader 
          python -m pip install --upgrade pip
          pip install httpx numpy
          pip install -r  requirements.txt 
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps          
      - name: run demo
        run: |
          cd tiktoka-studio-uploader 
          bash test.sh
      - name: Config git
        run: >
          git config --local user.email "ations@github.com"

          git config --local user.name "github"

          git config --global http.postBuffer 157286400

          git remote set-url origin "https://${{ github.actor }}:${{
          github.token }}@github.com/${{ github.repository }}"
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ github.run_id }}'
          prerelease: false
          title: '${{ github.run_id }}'
          files: |
            tiktoka-studio-uploader/output/*

```

all failed....
