### ISSUE TITLE
[Feature]: Add Support for specifying settings in pyproject.toml

### ISSUE THREAD

**Issue by aersam** [microsoft/playwright-python#2715]
### 🚀 Feature Request

There are settings that cannot be changed in Python (or, I did not find out, how). Eg, how to set video.size that you can do in TypeScript: https://playwright.dev/docs/api/class-testoptions/#test-options-video 

It would be best to have that available in pyproject.toml, similar to pyright or other tools

### Example

```toml
[tool.playwright.options]
video = { mode= "on", size= {height=1900, width=1080 }}
```

### Motivation

Make all options available in a pythonic way

**Comment by ltsuda** [comment]
This is how to configure browser's viewport using Playwright's Pytest plugin. The page you linked is specific for their Test Runner in JS/TS.

https://playwright.dev/python/docs/test-runners#use-custom-viewport-size

As you can see, you can override the `browser_context_args` fixture options, they are the same as here. 

https://playwright.dev/python/docs/api/class-browser#browser-new-context

There's `video` option, that if not specified, it's going to be the same as `viewport` or you can customized it too.

https://playwright.dev/python/docs/api/class-browser#browser-new-context-option-record-video-size

As they created a Pytest plugin, then the only way to configure on `pyproject.toml` is on the `pytest` section like below and only these [CLI Options](https://playwright.dev/python/docs/test-runners#cli-arguments):

```toml
[tool.pytest.ini_options]
# Run firefox with UI
addopts = "--headed --browser firefox --video=on"
```
