### ISSUE TITLE
[Feature]: add snapshotForAI support

### ISSUE THREAD

**Issue by wangzhe0912** [microsoft/playwright-python#2867]
### 🚀 Feature Request

add snapshotForAI support.
base Python version inplement PlayWright MCP Server。

### Motivation

base Python version inplement PlayWright MCP Server。

**Comment by changshuo08** [comment]
@latifboubyan  Could you give me some examples for mcp

**Comment by wangzhe0912** [comment]
Or exposing the forAI parameter in the ariaSnapshot method in the Node version would also work.

Attached is the ariaSnapshot definition from Node version 1.53:

```yaml
ariaSnapshot:
  title: Aria snapshot
  parameters:
    selector: string
    forAI: boolean?
    timeout: number
  returns:
    snapshot: string
  flags:
    snapshot: true
```

https://github.com/microsoft/playwright/blob/main/packages/protocol/src/protocol.yml#L2108
